# Generated by Django 4.1.1 on 2022-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 24 symbols', max_length=24, verbose_name='напиток')),
                ('capacity', models.DecimalField(decimal_places=2, default=0, help_text='Max 9.99', max_digits=3, verbose_name='объём напитка')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Max 99.99', max_digits=4, verbose_name='цена')),
                ('is_published', models.BooleanField(default=False, verbose_name='publication')),
            ],
            options={
                'db_table': 'app_drinks',
            },
        ),
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 24 symbols', max_length=24, verbose_name='ингридиент')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Max 999.99', max_digits=5, verbose_name='цена')),
            ],
            options={
                'db_table': 'app_ingridients',
            },
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 24 symbols', max_length=24, verbose_name='закуски')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Max 99.99', max_digits=4, verbose_name='цена')),
                ('descr', models.CharField(blank=True, help_text='Max 140 symbols', max_length=140, null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='publication')),
            ],
            options={
                'db_table': 'app_snacks',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 24 symbols', max_length=24, verbose_name='пицца')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Max 999.99', max_digits=5, verbose_name='цена')),
                ('descr', models.CharField(blank=True, default='лучшая пицца', help_text='Max 140 symbols', max_length=140, null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='publication')),
                ('ingridients', models.ManyToManyField(to='app.ingridients', verbose_name='ингридиенты')),
            ],
            options={
                'db_table': 'app_pizza',
            },
        ),
    ]
