# Generated by Django 4.1.1 on 2022-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingridients',
            field=models.ManyToManyField(related_name='fuck', to='app.ingridients', verbose_name='ингридиенты'),
        ),
    ]
