# Generated by Django 4.1.1 on 2022-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pizza_ingridients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingridients',
            field=models.ManyToManyField(related_name='ingridient', to='app.ingridients', verbose_name='ингридиенты'),
        ),
    ]
