# Generated by Django 4.1.1 on 2022-10-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_product_delete_drinks_delete_snacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='article',
        ),
    ]
