# Generated by Django 4.1.2 on 2022-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('email', models.CharField(max_length=77, verbose_name='почта')),
                ('message', models.CharField(max_length=1024, verbose_name='сообщение')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
                'db_table': 'app_contacts',
                'ordering': ('date_created',),
            },
        ),
        migrations.AddField(
            model_name='ingridients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='descr',
            field=models.CharField(blank=True, help_text='Max 140 symbols', max_length=140, null=True, verbose_name='описание'),
        ),
    ]
