# Generated by Django 4.1.2 on 2022-11-08 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=24, null=True, verbose_name='Если был такой title')),
                ('first_text', models.TextField(verbose_name='first text')),
                ('image_of_post1', models.ImageField(help_text='Обязательно', upload_to='posts/', verbose_name='image of post1')),
                ('image_of_post2', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='image of post2')),
                ('second_text', models.TextField(verbose_name='second text')),
                ('last_text', models.TextField(verbose_name='last text')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2022, 11, 8, 14, 0, 14, 743572, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('author', models.CharField(default='Pizzeria', max_length=24, verbose_name='Автор')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'db_table': 'blog_posts',
                'ordering': ('date_published',),
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 14, 0, 14, 727944, tzinfo=datetime.timezone.utc), verbose_name='дата'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2022, 11, 8, 14, 0, 14, 743572, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'app_comments',
                'ordering': ('date_published',),
            },
        ),
    ]
