# Generated by Django 4.1.2 on 2022-11-08 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_post_alter_contact_date_created_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 14, 16, 10, 608909, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 14, 16, 10, 608909, tzinfo=datetime.timezone.utc), verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 14, 16, 10, 608909, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_text',
            field=models.TextField(blank=True, null=True, verbose_name='last text'),
        ),
    ]
