# Generated by Django 4.1.2 on 2022-11-08 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preshow_text',
            field=models.CharField(default='вам следует это прочитать', help_text='MAX 90 symbols', max_length=90, verbose_name='Текст отображаемый в блоге'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 15, 40, 57, 941565, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 15, 40, 57, 941565, tzinfo=datetime.timezone.utc), verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 15, 40, 57, 941565, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
