# Generated by Django 4.1.2 on 2022-11-09 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_preshow_text_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text of comment'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 20, 50, 51, 367090, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 20, 50, 51, 362089, tzinfo=datetime.timezone.utc), verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 20, 50, 51, 365094, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
